### ISSUE TITLE
error angular npm install

### ISSUE THREAD

**Issue by selique** [loiane/curso-angular2#1]
PS C:\Users\moises.ferreira\Desktop\Projeto_Angular\01-helloworld> npm install
npm http GET https://registry.npmjs.org/systemjs
npm http GET https://registry.npmjs.org/angular2-in-memory-web-api
npm http GET https://registry.npmjs.org/bootstrap
npm http GET https://registry.npmjs.org/concurrently
npm http GET https://registry.npmjs.org/lite-server
npm http GET https://registry.npmjs.org/canonical-path
npm http GET https://registry.npmjs.org/http-server
npm http GET https://registry.npmjs.org/jasmine-core
npm http GET https://registry.npmjs.org/karma
npm http GET https://registry.npmjs.org/karma-chrome-launcher
npm http GET https://registry.npmjs.org/karma-cli
npm http GET https://registry.npmjs.org/karma-htmlfile-reporter
npm http GET https://registry.npmjs.org/karma-jasmine
npm http GET https://registry.npmjs.org/angular/router
npm http GET https://registry.npmjs.org/angular/forms
npm http GET https://registry.npmjs.org/angular/platform-browser-dynamic
npm http GET https://registry.npmjs.org/angular/http
npm http GET https://registry.npmjs.org/angular/platform-browser
npm http GET https://registry.npmjs.org/angular/router-deprecated
npm http GET https://registry.npmjs.org/angular/upgrade
npm http GET https://registry.npmjs.org/angular/common
npm http GET https://registry.npmjs.org/core-js
npm http GET https://registry.npmjs.org/rxjs
npm http GET https://registry.npmjs.org/reflect-metadata
npm http GET https://registry.npmjs.org/zone.js
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/tslint
npm http GET https://registry.npmjs.org/typings
npm http GET https://registry.npmjs.org/typescript
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/angular/core
npm http GET https://registry.npmjs.org/protractor
npm http GET https://registry.npmjs.org/angular/compiler
npm http 200 https://registry.npmjs.org/canonical-path
npm http 200 https://registry.npmjs.org/lite-server
npm http 200 https://registry.npmjs.org/concurrently
npm http 200 https://registry.npmjs.org/jasmine-core
npm http 304 https://registry.npmjs.org/core-js
npm http 304 https://registry.npmjs.org/tslint
npm http 304 https://registry.npmjs.org/lodash
npm http 200 https://registry.npmjs.org/bootstrap
npm http 200 https://registry.npmjs.org/karma-chrome-launcher
npm http 200 https://registry.npmjs.org/karma-cli
npm http 200 https://registry.npmjs.org/karma-htmlfile-reporter
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/typescript
npm http 304 https://registry.npmjs.org/protractor
npm http 200 https://registry.npmjs.org/http-server
npm http 404 https://registry.npmjs.org/angular/router
npm http 304 https://registry.npmjs.org/zone.js
npm http 304 https://registry.npmjs.org/typings
npm http 304 https://registry.npmjs.org/rxjs
npm http 200 https://registry.npmjs.org/karma-jasmine
npm http 200 https://registry.npmjs.org/angular2-in-memory-web-api
npm http 200 https://registry.npmjs.org/systemjs
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'angular/router' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'angular2-quickstart'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Windows_NT 10.0.14393
npm ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\moises.ferreira\Desktop\Projeto_Angular\01-helloworld
npm ERR! node -v v7.2.1
npm ERR! npm -v 1.4.9
npm ERR! code E404
npm http GET https://registry.npmjs.org/canonical-path/-/canonical-path-0.0.2.tgz
npm http GET https://registry.npmjs.org/concurrently/-/concurrently-2.2.0.tgz
npm http 404 https://registry.npmjs.org/angular/http
npm http 404 https://registry.npmjs.org/angular/platform-browser-dynamic
npm http 404 https://registry.npmjs.org/angular/forms
npm http GET https://registry.npmjs.org/rxjs/-/rxjs-5.0.0-beta.6.tgz
npm http GET https://registry.npmjs.org/jasmine-core/-/jasmine-core-2.4.1.tgz
npm http GET https://registry.npmjs.org/bootstrap/-/bootstrap-3.3.7.tgz
npm http 404 https://registry.npmjs.org/angular/common
npm http 404 https://registry.npmjs.org/angular/platform-browser
npm http 404 https://registry.npmjs.org/angular/upgrade
npm http GET https://registry.npmjs.org/karma-chrome-launcher/-/karma-chrome-launcher-0.2.3.tgz
npm http GET https://registry.npmjs.org/lite-server/-/lite-server-2.2.2.tgz
npm http GET https://registry.npmjs.org/karma-cli/-/karma-cli-0.1.2.tgz
npm http GET https://registry.npmjs.org/typescript/-/typescript-1.9.0-dev.20160627-1.0.tgz
npm http GET https://registry.npmjs.org/karma-htmlfile-reporter/-/karma-htmlfile-reporter-0.2.3.tgz
npm http GET https://registry.npmjs.org/typings/-/typings-1.5.0.tgz
npm http 304 https://registry.npmjs.org/reflect-metadata
npm http 404 https://registry.npmjs.org/angular/router-deprecated
npm http 404 https://registry.npmjs.org/angular/core
npm http GET https://registry.npmjs.org/http-server/-/http-server-0.9.0.tgz
npm http GET https://registry.npmjs.org/karma-jasmine/-/karma-jasmine-0.3.8.tgz
npm http GET https://registry.npmjs.org/angular2-in-memory-web-api/-/angular2-in-memory-web-api-0.0.14.tgz
npm http GET https://registry.npmjs.org/systemjs/-/systemjs-0.19.27.tgz
npm http 200 https://registry.npmjs.org/canonical-path/-/canonical-path-0.0.2.tgz
npm http 200 https://registry.npmjs.org/concurrently/-/concurrently-2.2.0.tgz
npm http 200 https://registry.npmjs.org/rxjs/-/rxjs-5.0.0-beta.6.tgz
npm http 404 https://registry.npmjs.org/angular/compiler
npm http 200 https://registry.npmjs.org/jasmine-core/-/jasmine-core-2.4.1.tgz
npm http 200 https://registry.npmjs.org/bootstrap/-/bootstrap-3.3.7.tgz
npm http 200 https://registry.npmjs.org/lite-server/-/lite-server-2.2.2.tgz
npm http 200 https://registry.npmjs.org/karma-chrome-launcher/-/karma-chrome-launcher-0.2.3.tgz
npm http 200 https://registry.npmjs.org/karma-cli/-/karma-cli-0.1.2.tgz
npm http 200 https://registry.npmjs.org/karma-htmlfile-reporter/-/karma-htmlfile-reporter-0.2.3.tgz
npm http 200 https://registry.npmjs.org/typings/-/typings-1.5.0.tgz
npm http 200 https://registry.npmjs.org/http-server/-/http-server-0.9.0.tgz
npm http 200 https://registry.npmjs.org/angular2-in-memory-web-api/-/angular2-in-memory-web-api-0.0.14.tgz
npm http 200 https://registry.npmjs.org/systemjs/-/systemjs-0.19.27.tgz
npm http 200 https://registry.npmjs.org/karma-jasmine/-/karma-jasmine-0.3.8.tgz
npm http 200 https://registry.npmjs.org/typescript/-/typescript-1.9.0-dev.20160627-1.0.tgz
npm http 200 https://registry.npmjs.org/karma
npm http GET https://registry.npmjs.org/karma/-/karma-0.13.22.tgz
npm http 200 https://registry.npmjs.org/karma/-/karma-0.13.22.tgz
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\moises.ferreira\Desktop\Projeto_Angular\01-helloworld\npm-debug.log
npm ERR! not ok code 0
PS C:\Users\moises.ferreira\Desktop\Projeto_Angular\01-helloworld> npm start

> angular2-quickstart@1.0.0 start C:\Users\moises.ferreira\Desktop\Projeto_Angular\01-helloworld
> tsc && concurrently "tsc -w" "lite-server"

app/app.component.spec.ts(4,31): error TS2307: Cannot find module '@angular/core/testing'.
app/app.component.spec.ts(6,38): error TS2307: Cannot find module '@angular/core/testing'.
app/app.component.spec.ts(8,32): error TS2307: Cannot find module '@angular/platform-browser'.
app/app.component.spec.ts(9,32): error TS2307: Cannot find module '@angular/core'. app/app.component.spec.ts(10,32): error TS2307: Cannot find module '@angular/core'.

app/app.component.spec.ts(11,32): error TS2307: Cannot find module '@angular/core/src/facade/promise'.
app/app.component.spec.ts(16,1): error TS2304: Cannot find name 'describe'.
app/app.component.spec.ts(17,3): error TS2304: Cannot find name 'it'.
app/app.component.spec.ts(18,5): error TS2304: Cannot find name 'expect'.
app/app.component.spec.ts(22,1): error TS2304: Cannot find name 'describe'.
app/app.component.spec.ts(24,3): error TS2304: Cannot find name 'it'.
app/app.component.spec.ts(27,40): error TS7006: Parameter 'fixture' implicitly has an 'any' type.
app/app.component.spec.ts(28,7): error TS2304: Cannot find name 'expect'.
app/app.component.spec.ts(32,3): error TS2304: Cannot find name 'it'.
app/app.component.spec.ts(35,42): error TS7006: Parameter 'fixture' implicitly has an 'any' type.
app/app.component.spec.ts(38,43): error TS7006: Parameter 'el' implicitly has an 'any' type.
app/app.component.spec.ts(42,7): error TS2304: Cannot find name 'expect'.
app/app.component.ts(1,27): error TS2307: Cannot find module '@angular/core'.
app/main.ts(1,30): error TS2307: Cannot find module '@angular/platform-browser-dynamic'.
e2e/app.e2e-spec.ts(2,1): error TS2304: Cannot find name 'describe'.
e2e/app.e2e-spec.ts(7,3): error TS2304: Cannot find name 'beforeEach'.
e2e/app.e2e-spec.ts(8,5): error TS2304: Cannot find name 'browser'.
e2e/app.e2e-spec.ts(11,3): error TS2304: Cannot find name 'it'.
e2e/app.e2e-spec.ts(12,5): error TS2304: Cannot find name 'expect'.
e2e/app.e2e-spec.ts(12,12): error TS2304: Cannot find name 'element'.
e2e/app.e2e-spec.ts(12,20): error TS2304: Cannot find name 'by'.

npm ERR! angular2-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular2-quickstart@1.0.0 start script.
npm ERR! This is most likely a problem with the angular2-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "lite-server"
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-quickstart
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 10.0.14393
npm ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! cwd C:\Users\moises.ferreira\Desktop\Projeto_Angular\01-helloworld
npm ERR! node -v v7.2.1
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\moises.ferreira\Desktop\Projeto_Angular\01-helloworld\npm-debug.log
npm ERR! not ok code 0
PS C:\Users\moises.ferreira\Desktop\Projeto_Angular\01-helloworld>

**Comment by violettwelt** [comment]
Caramba! Creio que nao fez a instalação do Node.js corretamente, pois o npm já vem na instalação do node. 
Dica: Alguns erros do npm são das divergências de onde está salvo o seu repositório, confira corretamente, onde estão sendo salvos.
Para seguir corretamente, confira os videos da [loiane](
https://github.com/loiane), eu apenas copiei a aula desse projeto para o meu github.

Abraços!
Violett.

**Comment by temistoclesarea** [comment]
Se o problema for Proxy
Configure o `npm`:

> `npm config set proxy http://proxy.company.com:8080`
`npm config set https-proxy http://proxy.company.com:8080` 

Tambem configure o `Typings` para proxy e crie um arquivo na raiz `.typingsrc` e coloque o seguinte conteúdo: 
> `proxy=http://proxy.company.com:8080`
`rejectUnauthorized=false`

Comigo resolveu o problema
