### ISSUE TITLE
ng serve retorna um erro ?

### ISSUE THREAD

**Issue by DevJoseWeb** [loiane/curso-angular2#2]
Tentando rodar o projeto para acompanhar o curso, e estou pegando isso na hora de rodar o ng serve, do que se trata ?

Obrigado !

root@ubuntux:/home/jr/projetos/primeiro-projeto# ng serve
Environment configuration does not contain "environmentSource" entry.

A new environmentSource entry replaces the previous source entry inside environments.
(Uma nova entrada environmentSource substitui a entrada de origem anterior dentro de ambientes.)

To migrate angular-cli.json follow the example below:

Before:

"environments": {
  "source": "environments/environment.ts",
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}

After:

"environmentSource": "environments/environment.ts",
"environments": {
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}

**Comment by Parreira16** [comment]
O angular teve atualizações, para o projeto rodar tem que fazer atualização no environments, você deve pegar o arquivo angular-cli.json e mudar o environments.
Exemplo na linha 24
https://github.com/loiane/curso-angular2/blob/master/primeiro-projeto/angular-cli.json
Tem que ficar igual a este outro projeto na linha 28
https://github.com/loiane/curso-angular2/blob/master/_07-rotas/.angular-cli.json

Creio que criar um novo projeto ng new priemeiro-projeto2 e copiar a pasta app deva solucionar o problema também.

**Comment by DevJuniorFerreira** [comment]
Obrigado !
