### ISSUE TITLE
Menu alunos dá erro.

### ISSUE THREAD

**Issue by marcellopato** [loiane/curso-angular2#3]
Olá pessoal, eu não sei porque, meu menu alunos não funciona, dá sempre o erro abaixo:

`error_handler.js:48 EXCEPTION: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'alunos'
Error: Cannot match any routes. URL Segment: 'alunos'`

E eu até já baixei os arquivos do projeto e coloquei no lugar do meu. Alguma dica?
Obrigado!

**Comment by loiane** [comment]
Oi @marcellopato conseguiu resolver ou o erro ainda ocorre?

**Comment by marcellopato** [comment]
Oi Loiane, eu mudei de Angular para Laravel… !
Obrigado pela resposta!

Beijos!




Marcello Pato
marcellocorreia@gmail.com
(11) 97572-7699

**Comment by loiane** [comment]
Blz! Vou fechar a issue então! []s
